### ISSUE TITLE
📘 [issue] - README.md file is not configured and visible in the repository's main branch

### ISSUE THREAD

**Issue by divyanshudhruv** [INeedJobToStartWork/Commit-Smile#8]
### Related page

README.md

### Kind of issue

Other

### Issue Description

Update the README.md file so that it can be visible in the repository's main branch and make the README file more informative by including the steps, features etc.

![image](https://github.com/INeedJobToStartWork/Commit-Smile/assets/71079602/e1d1265f-27ae-4234-af72-0afd78f87bb5)

### Context

I was trying to look into the code after the release, and then I came across this issue.

### Scale of problem

1 - Not annoying

**Comment by INeedJobToStartWork** [comment]
I noticed it before but hadnt time to fix it, today all will be fine :)

**Comment by divyanshudhruv** [comment]
Ok !
